spring.application.name=attendancemanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=postgres
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL???????
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# MyBatis??
mybatis.type-aliases-package=jp.educure.attendancemanagement.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:/mapper/*.xml

# JWT
app.jwt.secret=jnWxRU6efprk7TLiD66iWkx6AL9hhDJkUgfJizQLymZgUnQVwxjkGLexKA9bTTaUuse9AFYHbSkehPjzZgfuFVLiF9V6GN8JNrubTPtWcGCykt8zEVr33L4Z4H8EddBHAuTinGXgB6MA8Zgk2CCewz
app.jwt.expiration-ms=86400000
